//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryEntity()
        {
            this.ItemEntities = new HashSet<ItemEntity>();
        }
    
        public int InventoryId { get; set; }
        public int OwnerId { get; set; }
    
        public virtual OwnerEntity OwnerEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemEntity> ItemEntities { get; set; }
    }
}
