//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEntity
    {
        public int ItemId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public string Condition { get; set; }
        public bool IsAvailable { get; set; }
        public int InventoryId { get; set; }
        public Nullable<int> TransactionId { get; set; }
    
        public virtual InventoryEntity InventoryEntity { get; set; }
        public virtual TransactionEntity TransactionEntity { get; set; }
    }
}
