//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OwnerEntity()
        {
            this.InventoryEntities = new HashSet<InventoryEntity>();
        }
    
        public int OwnerId { get; set; }
        public string Contact { get; set; }
        public int OwnerRating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryEntity> InventoryEntities { get; set; }
    }
}
