//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RenterEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RenterEntity()
        {
            this.TransactionEntities = new HashSet<TransactionEntity>();
        }
    
        public int RenterId { get; set; }
        public string Contact { get; set; }
        public int RenterRating { get; set; }
        public bool IsRenting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionEntity> TransactionEntities { get; set; }
    }
}
